import type { EventBriefValues } from "@/components/EventBriefEditor";

export type EventScenario = {
  id: string;
  label: string;
  brief: EventBriefValues;
};

export const EVENT_SCENARIOS: EventScenario[] = [
  {
    id: "conference-clients-lunch",
    label: "Conference + lunch meeting",
    brief: {
      dressCode: ["Business Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Conference"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "55°F, light breeze",
      purpose: "Work Event",
      purposeOther: "",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "Half day",
      durationOther: "",
      audience: "Clients",
      audienceOther: "",
      notes: "needs to transition into a lunch meeting",
    },
  },
  {
    id: "rooftop-birthday-bold",
    label: "Rooftop birthday",
    brief: {
      dressCode: ["Smart Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Rooftop"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "cool breeze (~60°F)",
      purpose: "Birthday",
      purposeOther: "",
      styleMood: "Bold",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "wind exposure may affect hair and outfit flow",
    },
  },
  {
    id: "cocktail-date-restaurant",
    label: "Cocktail date dinner",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Both",
      venue: ["Restaurant"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "cold (~45°F)",
      purpose: "Date Night",
      purposeOther: "",
      styleMood: "Elegant",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Date",
      audienceOther: "",
      notes: "indoor heating vs outdoor chill",
    },
  },
  {
    id: "park-minimal-walk",
    label: "Park walk, minimalist",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Park"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "sunny (~70°F)",
      purpose: "Vacation",
      purposeOther: "",
      styleMood: "Minimalist",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "Under 2 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "walking and sitting on grass",
    },
  },
  {
    id: "dog-park-playtime",
    label: "Dog park playtime",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: [],
      venueOther: "Dog park",
      timeOfDay: "Daytime",
      weather: "mild (~65°F)",
      purpose: "Travel",
      purposeOther: "Dog walk / pet playtime",
      styleMood: "Street Smart",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "Under 2 hours",
      durationOther: "",
      audience: "Solo",
      audienceOther: "",
      notes: "high activity, possible dirt, bending and movement",
    },
  },
  {
    id: "wedding-ballroom-all-day",
    label: "Wedding guest ballroom",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Ballroom"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "mild (~68°F)",
      purpose: "Wedding Guest",
      purposeOther: "",
      styleMood: "Elegant",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "All day",
      durationOther: "",
      audience: "Family",
      audienceOther: "",
      notes: "dancing and photographs expected",
    },
  },
  {
    id: "beach-romantic-vacation",
    label: "Beach vacation",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Beach"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "warm sunny (~80°F)",
      purpose: "Vacation",
      purposeOther: "",
      styleMood: "Romantic",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "UV exposure, wind, and sand",
    },
  },
  {
    id: "conference-all-day-colleagues",
    label: "Conference all day",
    brief: {
      dressCode: ["Business Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Conference"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "indoor AC (~68°F)",
      purpose: "Work Event",
      purposeOther: "",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "All day",
      durationOther: "",
      audience: "Colleagues",
      audienceOther: "",
      notes: "long standing and walking periods",
    },
  },
  {
    id: "winery-photo-friendly",
    label: "Winery day out",
    brief: {
      dressCode: ["Smart Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Winery"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "pleasant (~72°F)",
      purpose: "Vacation",
      purposeOther: "",
      styleMood: "Elegant",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "photo-friendly setting with walking between tasting areas",
    },
  },
  {
    id: "home-party-floor-seating",
    label: "Home party",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: [],
      venueOther: "Home",
      timeOfDay: "Nighttime",
      weather: "indoor cozy weather",
      purpose: "Party",
      purposeOther: "",
      styleMood: "Minimalist",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "floor seating possible",
    },
  },
  {
    id: "museum-cultural-date",
    label: "Museum cultural outing",
    brief: {
      dressCode: ["Smart Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Museum"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "cool indoor (~65°F)",
      purpose: "Date Night",
      purposeOther: "Cultural outing",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Date",
      audienceOther: "",
      notes: "quiet setting with a lot of walking",
    },
  },
  {
    id: "bar-party-sexy",
    label: "Bar party",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Bar"],
      venueOther: "",
      timeOfDay: "Nighttime",
      weather: "warm crowded indoor (~75°F)",
      purpose: "Party",
      purposeOther: "",
      styleMood: "Sexy",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "heat, dancing, and close crowding",
    },
  },
  {
    id: "cafe-remote-work",
    label: "Cafe remote work",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: [],
      venueOther: "Cafe",
      timeOfDay: "Daytime",
      weather: "mild (~68°F)",
      purpose: "Work Event",
      purposeOther: "Remote work session",
      styleMood: "Minimalist",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "Half day",
      durationOther: "",
      audience: "Solo",
      audienceOther: "",
      notes: "sitting posture and laptop use matter",
    },
  },
  {
    id: "park-light-hiking",
    label: "Light hiking in park",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Park"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "cool (~60°F)",
      purpose: "Vacation",
      purposeOther: "Light hiking",
      styleMood: "Street Smart",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "terrain, movement, and layering needed",
    },
  },
  {
    id: "hotel-festive-celebration",
    label: "Festive hotel celebration",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Both",
      venue: ["Hotel"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "cool (~65°F)",
      purpose: "Party",
      purposeOther: "Festive cultural celebration",
      styleMood: "Bold",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Family",
      audienceOther: "",
      notes: "mix of indoor ballroom and outdoor arrival areas",
    },
  },
  {
    id: "startup-networking",
    label: "Startup networking",
    brief: {
      dressCode: ["Smart Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Conference"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "mild (~67°F)",
      purpose: "Work Event",
      purposeOther: "Startup networking",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Colleagues",
      audienceOther: "young professionals",
      notes: "networking heavy, standing and introductions",
    },
  },
  {
    id: "tennis-practice",
    label: "Tennis practice",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Sports"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "warm (~75°F)",
      purpose: "Travel",
      purposeOther: "Tennis practice",
      styleMood: "Street Smart",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "Under 2 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "mobility and sweat management are critical",
    },
  },
  {
    id: "airport-travel-day",
    label: "Airport travel day",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Travel"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "airport AC (~68°F)",
      purpose: "Travel",
      purposeOther: "",
      styleMood: "Minimalist",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "All day",
      durationOther: "",
      audience: "Solo",
      audienceOther: "",
      notes: "security lines, long sitting, and temperature shifts",
    },
  },
  {
    id: "picnic-date",
    label: "Picnic date",
    brief: {
      dressCode: ["Smart Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Park"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "pleasant (~72°F)",
      purpose: "Date Night",
      purposeOther: "Picnic date",
      styleMood: "Romantic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Date",
      audienceOther: "",
      notes: "picnic setup and grass seating",
    },
  },
  {
    id: "holiday-market-cold",
    label: "Holiday market",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: [],
      venueOther: "Holiday market",
      timeOfDay: "Evening",
      weather: "cold (~35°F)",
      purpose: "Vacation",
      purposeOther: "Festive outing",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "layering needed for standing outdoors with hot drinks",
    },
  },
  {
    id: "rainy-date-night",
    label: "Rainy date night",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Both",
      venue: ["Restaurant"],
      venueOther: "",
      timeOfDay: "Evening",
      weather: "heavy rain (~50°F)",
      purpose: "Date Night",
      purposeOther: "",
      styleMood: "Elegant",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Date",
      audienceOther: "",
      notes: "heels vs puddles conflict",
    },
  },
  {
    id: "extreme-cold-dog-walk",
    label: "Extreme cold dog walk",
    brief: {
      dressCode: ["Casual"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Park"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "extreme cold (~25°F)",
      purpose: "Travel",
      purposeOther: "Dog walk",
      styleMood: "Minimalist",
      styleMoodOther: "",
      comfortOrFashion: "Comfort",
      duration: "Under 2 hours",
      durationOther: "",
      audience: "Solo",
      audienceOther: "",
      notes: "warmth matters more than style",
    },
  },
  {
    id: "rooftop-temp-drop",
    label: "Rooftop temperature drop",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Outdoor",
      venue: ["Rooftop"],
      venueOther: "",
      timeOfDay: "Nighttime",
      weather: "unexpected temperature drop (~45°F)",
      purpose: "Party",
      purposeOther: "",
      styleMood: "Bold",
      styleMoodOther: "",
      comfortOrFashion: "Fashion",
      duration: "2-4 hours",
      durationOther: "",
      audience: "Friends",
      audienceOther: "",
      notes: "no outerwear planned initially",
    },
  },
  {
    id: "humid-ballroom-wedding",
    label: "Humid ballroom wedding",
    brief: {
      dressCode: ["Cocktail"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Ballroom"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "very hot humid (~90°F)",
      purpose: "Wedding Guest",
      purposeOther: "",
      styleMood: "Elegant",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "All day",
      durationOther: "",
      audience: "Family",
      audienceOther: "",
      notes: "heavy fabrics vs sweat conflict",
    },
  },
  {
    id: "interview-unknown-dress-code",
    label: "Interview, unknown dress code",
    brief: {
      dressCode: ["Business Casual"],
      dressCodeOther: "",
      location: "Indoor",
      venue: ["Conference"],
      venueOther: "",
      timeOfDay: "Daytime",
      weather: "unknown indoor conditions",
      purpose: "Interview",
      purposeOther: "",
      styleMood: "Classic",
      styleMoodOther: "",
      comfortOrFashion: "Balanced",
      duration: "Half day",
      durationOther: "",
      audience: "Clients",
      audienceOther: "new employer and interview panel",
      notes: "uncertain dress code norms",
    },
  },
];
