begin;

insert into public.style_catalog (style_key, label, dimension, description, aliases, sort_order, is_active)
values
  ('tailored', 'Tailored', 'silhouette', 'Clean, shaped, precise through the body.', '["structured tailoring", "shaped"]'::jsonb, 1, true),
  ('structured', 'Structured', 'silhouette', 'Built with clear lines and visible shape.', '["sharp", "architectural"]'::jsonb, 2, true),
  ('relaxed', 'Relaxed', 'silhouette', 'Easy, unfussy, and comfortable without feeling sloppy.', '["easy", "casual"]'::jsonb, 3, true),
  ('oversized', 'Oversized', 'silhouette', 'Intentional volume with a loose, roomy shape.', '["boxy", "baggy"]'::jsonb, 4, true),
  ('fitted', 'Fitted', 'silhouette', 'Close to the body and visually clean.', '["slim", "snug"]'::jsonb, 5, true),
  ('flowing', 'Flowing', 'silhouette', 'Soft movement and fluid drape.', '["draped", "fluid"]'::jsonb, 6, true),
  ('sharp', 'Sharp', 'silhouette', 'Crisp edges and defined lines.', '["clean line"]'::jsonb, 7, true),
  ('longline', 'Longline', 'silhouette', 'Extended length that elongates the body.', '["elongated"]'::jsonb, 8, true),
  ('cropped', 'Cropped', 'silhouette', 'Shortened length that reveals the waist or ankle.', '["shortened"]'::jsonb, 9, true),
  ('a_line', 'A-line', 'silhouette', 'Flares gently away from the body.', '["fit and flare"]'::jsonb, 10, true),
  ('bodycon', 'Bodycon', 'silhouette', 'Very close fit with a body-skimming line.', '["figure-hugging"]'::jsonb, 11, true),
  ('draped', 'Draped', 'silhouette', 'Soft folds or gathered structure shape the garment.', '["gathered"]'::jsonb, 12, true),
  ('boxy', 'Boxy', 'silhouette', 'Square cut with a straight outline.', '["square cut"]'::jsonb, 13, true),
  ('cinched', 'Cinched', 'silhouette', 'Pulled in at the waist or body to define shape.', '["waisted"]'::jsonb, 14, true),
  ('wool', 'Wool', 'fabric', 'Warm, insulating, cool-weather weight.', '["knit wool"]'::jsonb, 20, true),
  ('knit', 'Knit', 'fabric', 'Looped or sweater-like texture.', '["sweater knit"]'::jsonb, 21, true),
  ('linen', 'Linen', 'fabric', 'Breathable, airy, and warm-weather friendly.', '["linen blend"]'::jsonb, 22, true),
  ('denim', 'Denim', 'fabric', 'Sturdy woven cotton with a casual edge.', '["jean"]'::jsonb, 23, true),
  ('satin', 'Satin', 'fabric', 'Smooth, reflective, and softly glossy.', '["silky"]'::jsonb, 24, true),
  ('silk', 'Silk', 'fabric', 'Light, fluid, and refined.', '["silken"]'::jsonb, 25, true),
  ('leather', 'Leather', 'fabric', 'Smooth or textured leather finish.', '["faux leather"]'::jsonb, 26, true),
  ('suede', 'Suede', 'fabric', 'Soft brushed leather surface.', '["nubuck"]'::jsonb, 27, true),
  ('tweed', 'Tweed', 'fabric', 'Dense, textured, heritage fabric.', '["boucle", "herringbone"]'::jsonb, 28, true),
  ('lace', 'Lace', 'fabric', 'Openwork, delicate, and decorative.', '["sheer lace"]'::jsonb, 29, true),
  ('mesh', 'Mesh', 'fabric', 'Open, airy, and lightly transparent.', '["net"]'::jsonb, 30, true),
  ('chiffon', 'Chiffon', 'fabric', 'Sheer, floaty, and airy.', '["floaty"]'::jsonb, 31, true),
  ('cotton', 'Cotton', 'fabric', 'Natural, breathable, everyday fabric.', '["cotton blend"]'::jsonb, 32, true),
  ('textured', 'Textured', 'fabric', 'Noticeable surface texture or weave.', '["heathered", "ribbed"]'::jsonb, 33, true),
  ('solid', 'Solid', 'pattern', 'Single tone or unpatterned surface.', '["plain"]'::jsonb, 40, true),
  ('plaid', 'Plaid', 'pattern', 'Checks, tartan, or plaid grid.', '["tartan", "check"]'::jsonb, 41, true),
  ('stripe', 'Stripe', 'pattern', 'Striped or pinstripe surface.', '["striped"]'::jsonb, 42, true),
  ('floral', 'Floral', 'pattern', 'Flower-based print or embroidery.', '["botanical"]'::jsonb, 43, true),
  ('animal_print', 'Animal Print', 'pattern', 'Leopard, zebra, snake, or similar animal-inspired print.', '["leopard", "zebra", "snake"]'::jsonb, 44, true),
  ('polka_dot', 'Polka Dot', 'pattern', 'Dot-based repeat print.', '["dots"]'::jsonb, 45, true),
  ('geometric', 'Geometric', 'pattern', 'Angular or repeated geometric print.', '["graphic"]'::jsonb, 46, true),
  ('abstract', 'Abstract', 'pattern', 'Painterly or non-literal print.', '["art print"]'::jsonb, 47, true),
  ('neutral', 'Neutral', 'color_family', 'Soft, muted, and easy-to-pair tones.', '["neutrals"]'::jsonb, 60, true),
  ('monochrome', 'Monochrome', 'color_family', 'Single-color story or near-single palette.', '["tonal"]'::jsonb, 61, true),
  ('warm', 'Warm', 'color_family', 'Warm undertone palette.', '["golden"]'::jsonb, 62, true),
  ('cool', 'Cool', 'color_family', 'Cool undertone palette.', '["icy"]'::jsonb, 63, true),
  ('earth', 'Earth', 'color_family', 'Olive, rust, camel, brown, and other grounded tones.', '["earthy"]'::jsonb, 64, true),
  ('bright', 'Bright', 'color_family', 'Clear, vivid, or saturated color story.', '["vibrant"]'::jsonb, 65, true),
  ('dark', 'Dark', 'color_family', 'Deep or low-light palette.', '["deep tone"]'::jsonb, 66, true),
  ('soft_pastel', 'Soft Pastel', 'color_family', 'Light, gentle, and airy palette.', '["pastel"]'::jsonb, 67, true),
  ('minimal', 'Minimal', 'vibe', 'Clean, quiet, and restrained.', '["clean"]'::jsonb, 80, true),
  ('polished', 'Polished', 'vibe', 'Finished, composed, and deliberate.', '["refined"]'::jsonb, 81, true),
  ('romantic', 'Romantic', 'vibe', 'Soft, feminine, and charming.', '["soft feminine"]'::jsonb, 82, true),
  ('playful', 'Playful', 'vibe', 'Light, fun, and a little unexpected.', '["fun"]'::jsonb, 83, true),
  ('classic', 'Classic', 'vibe', 'Timeless and familiar in a good way.', '["timeless"]'::jsonb, 84, true),
  ('modern', 'Modern', 'vibe', 'Current and crisp without feeling trendy-first.', '["contemporary"]'::jsonb, 85, true),
  ('dramatic', 'Dramatic', 'vibe', 'High contrast, strong presence, or statement energy.', '["bold"]'::jsonb, 86, true),
  ('edgy', 'Edgy', 'vibe', 'Sharper, cooler, or slightly rebellious.', '["cool-girl"]'::jsonb, 87, true),
  ('elevated', 'Elevated', 'vibe', 'Polished but not overly formal.', '["upsized"]'::jsonb, 88, true),
  ('casual', 'Casual', 'vibe', 'Relaxed everyday ease.', '["everyday"]'::jsonb, 89, true),
  ('statement', 'Statement', 'vibe', 'Designed to stand out and get noticed.', '["bold statement"]'::jsonb, 90, true),
  ('cozy', 'Cozy', 'vibe', 'Soft, warm, and comfortable.', '["snug"]'::jsonb, 91, true),
  ('layered', 'Layered', 'styling_detail', 'Built from multiple visible layers.', '["stacked"]'::jsonb, 92, true),
  ('clean', 'Clean', 'styling_detail', 'No-fuss styling with minimal clutter.', '["simple"]'::jsonb, 93, true),
  ('sleek', 'Sleek', 'styling_detail', 'Smooth, streamlined, and neat.', '["streamlined"]'::jsonb, 94, true),
  ('feminine', 'Feminine', 'styling_detail', 'Soft, graceful, and traditionally feminine styling cues.', '["soft feminine"]'::jsonb, 95, true),
  ('sporty', 'Sporty', 'styling_detail', 'Athletic or activewear-inspired styling.', '["athletic"]'::jsonb, 96, true),
  ('structured_detail', 'Structured', 'styling_detail', 'Visible tailoring or strong shape in the detailing.', '["sharp detail"]'::jsonb, 97, true),
  ('top', 'Top', 'garment_type', 'Upper-body garment.', '["tops"]'::jsonb, 110, true),
  ('bottom', 'Bottom', 'garment_type', 'Lower-body garment.', '["bottoms"]'::jsonb, 111, true),
  ('dress', 'Dress', 'garment_type', 'One-piece dress garment.', '["dresses"]'::jsonb, 112, true),
  ('jumpsuit', 'Jumpsuit', 'garment_type', 'One-piece jumpsuit or romper silhouette.', '["romper", "playsuit"]'::jsonb, 113, true),
  ('outerwear', 'Outerwear', 'garment_type', 'Coats, jackets, blazers, and layers.', '["layer"]'::jsonb, 114, true),
  ('shoes', 'Shoes', 'garment_type', 'Footwear and shoe styling.', '["footwear"]'::jsonb, 115, true),
  ('accessory', 'Accessory', 'garment_type', 'Bags, belts, scarves, hats, sunglasses, and hair accessories as non-jewelry finishing pieces.', '["accessories", "hair accessories", "hair accessory", "headband", "barrette", "claw clip"]'::jsonb, 116, true),
  ('jewelry', 'Jewelry', 'garment_type', 'Necklaces, earrings, bracelets, rings, watches, and other jewelry pieces.', '["jewellery"]'::jsonb, 117, true),
  ('set', 'Set', 'garment_type', 'Matching two-piece outfit.', '["coord", "co-ord"]'::jsonb, 118, true),
  ('swimwear', 'Swimwear', 'garment_type', 'Swim and resort garments.', '["swim"]'::jsonb, 119, true),
  ('loungewear', 'Loungewear', 'garment_type', 'Comfort-focused indoor or at-home wear.', '["lounge"]'::jsonb, 120, true),
  ('spring', 'Spring', 'season', 'Light layering and mild-weather dressing.', '["spring weather"]'::jsonb, 130, true),
  ('summer', 'Summer', 'season', 'Hot-weather, breathable dressing.', '["summer weather"]'::jsonb, 131, true),
  ('fall', 'Fall', 'season', 'Cool-weather, medium-weight dressing.', '["autumn"]'::jsonb, 132, true),
  ('winter', 'Winter', 'season', 'Cold-weather, insulating dressing.', '["winter weather"]'::jsonb, 133, true),
  ('all', 'All Season', 'season', 'Works year-round.', '["all-season"]'::jsonb, 134, true),
  ('casual_event', 'Casual', 'occasion', 'Easy, informal social setting.', '["casual occasion"]'::jsonb, 150, true),
  ('smart_casual', 'Smart Casual', 'occasion', 'Polished but relaxed.', '["smart casual"]'::jsonb, 151, true),
  ('business', 'Business', 'occasion', 'Work or professional setting.', '["office"]'::jsonb, 152, true),
  ('formal', 'Formal', 'occasion', 'Dress-up, event, or refined evening setting.', '["dressy"]'::jsonb, 153, true),
  ('party', 'Party', 'occasion', 'Social or celebratory setting.', '["night out"]'::jsonb, 154, true),
  ('date', 'Date', 'occasion', 'Date-night, romantic, or intimate setting.', '["date night"]'::jsonb, 155, true),
  ('travel', 'Travel', 'occasion', 'Packable, movable, and comfortable for transit.', '["airport"]'::jsonb, 156, true),
  ('resort', 'Resort', 'occasion', 'Vacation, destination, or leisure styling.', '["vacation"]'::jsonb, 157, true)
on conflict (style_key) do update set
  label = excluded.label,
  dimension = excluded.dimension,
  description = excluded.description,
  aliases = excluded.aliases,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

commit;
